**Question 01**

In [43]:
import random
import numpy as np

# Part a: A list of GPAs between 2.0 and 4.0
student_gpas = [round(random.uniform(2.0, 4.0), 2) for _ in range(20)]
print("Student gpas:", student_gpas)

# Part b: The highest two and lowest two GPAs
sorted_student_gpas = sorted(student_gpas)
highest_two = sorted_student_gpas[-2:]
lowest_two = sorted_student_gpas[:2]
print("Highest two gpas:", highest_two)
print("Lowest two gpas:", lowest_two)

# Part c: Dropping highest and lowest and calculate new list and average
new_gpas = sorted_student_gpas[2:-2]
average_gpa = round(np.mean(new_gpas), 2)
print("New list of gpas:", new_gpas)
print("Average gpa:", average_gpa)

# Part d: Switch the first and second halves of the list
n = len(student_gpas)
# Spliting the list into two halves and swaping their positions
rearranged_gpas = student_gpas[n//2:] + student_gpas[:n//2]
print("Original gpas:", student_gpas)
print("Rearranged gpas:", rearranged_gpas)

Student gpas: [2.72, 3.25, 2.05, 3.5, 3.68, 3.87, 3.14, 2.68, 3.21, 2.45, 3.91, 2.81, 3.06, 2.7, 2.58, 3.71, 3.21, 3.95, 2.99, 2.41]
Highest two gpas: [3.91, 3.95]
Lowest two gpas: [2.05, 2.41]
New list of gpas: [2.45, 2.58, 2.68, 2.7, 2.72, 2.81, 2.99, 3.06, 3.14, 3.21, 3.21, 3.25, 3.5, 3.68, 3.71, 3.87]
Average gpa: 3.1
Original gpas: [2.72, 3.25, 2.05, 3.5, 3.68, 3.87, 3.14, 2.68, 3.21, 2.45, 3.91, 2.81, 3.06, 2.7, 2.58, 3.71, 3.21, 3.95, 2.99, 2.41]
Rearranged gpas: [3.91, 2.81, 3.06, 2.7, 2.58, 3.71, 3.21, 3.95, 2.99, 2.41, 2.72, 3.25, 2.05, 3.5, 3.68, 3.87, 3.14, 2.68, 3.21, 2.45]


In [44]:
# Part e: Repeating all operations using NumPy
gpas_np = np.array(student_gpas)
print("Student gpas (using NumPy):", student_gpas)

# Highest and Lowest
highest_two_np = np.sort(gpas_np)[-2:]
lowest_two_np = np.sort(gpas_np)[:2]
print("Highest two gpas (using NumPy): ", highest_two_np)
print("Lowest two gpas (using NumPy): ", lowest_two_np)

# Dropping highest and lowest and calculate average
new_gpas_np = np.sort(gpas_np)[2:-2]
average_gpa_np = round(np.mean(new_gpas_np), 2)
print("New ilst (using NumPy): ", new_gpas_np)
print("Average gpa (using NumPy): ", average_gpa_np)

# Rearrange halves
rearranged_gpas_np = np.concatenate((gpas_np[n//2:], gpas_np[:n//2]))
print("Original gpas:", student_gpas)
print("Rearranged gpas (using NumPy):", rearranged_gpas_np)

Student gpas (using NumPy): [2.72, 3.25, 2.05, 3.5, 3.68, 3.87, 3.14, 2.68, 3.21, 2.45, 3.91, 2.81, 3.06, 2.7, 2.58, 3.71, 3.21, 3.95, 2.99, 2.41]
Highest two gpas (using NumPy):  [3.91 3.95]
Lowest two gpas (using NumPy):  [2.05 2.41]
New ilst (using NumPy):  [2.45 2.58 2.68 2.7  2.72 2.81 2.99 3.06 3.14 3.21 3.21 3.25 3.5  3.68
 3.71 3.87]
Average gpa (using NumPy):  3.1
Original gpas: [2.72, 3.25, 2.05, 3.5, 3.68, 3.87, 3.14, 2.68, 3.21, 2.45, 3.91, 2.81, 3.06, 2.7, 2.58, 3.71, 3.21, 3.95, 2.99, 2.41]
Rearranged gpas (using NumPy): [3.91 2.81 3.06 2.7  2.58 3.71 3.21 3.95 2.99 2.41 2.72 3.25 2.05 3.5
 3.68 3.87 3.14 2.68 3.21 2.45]


**Looking at the outputs, we can see that there actually aren't any numerical differences between the Python and NumPy results because they produced exactly the same values.**

**Question 02**

In [45]:
import numpy as np

# Part a: array of shape (5, 5) filled with random integers between 1 and 20 and replace third column with 1
array_a = np.random.randint(1, 21, size=(5, 5))
array_a[:, 2] = 1
print("a. (5,5) shape array with third column as 1:")
print(array_a)
print()

# Part b: (4,4) shape array with diagonal as 0
array_b = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(array_b, 0)
print("b. (4,4) shape array with diagonal as 0:")
print(array_b)
print()

# Part c: (5,5) shape array with integers in the range of 0 to 100 and extract border elements
array_c = np.random.randint(0, 101, size=(5, 5))
print("c. Original (5,5) shape array:")
print(array_c)

# Getting border elements
border_elements = np.concatenate([
    array_c[0, :-1],   # Top row
    array_c[:-1, -1],  # Right column
    array_c[-1, :0:-1],# Bottom row
    array_c[:0:-1, 0]  # Left column
])

# Getting corners
corners = array_c[[0, 0, -1, -1], [0, -1, 0, -1]]

print("Border elements:", border_elements)
print("Corner elements:", corners)
print()

# Part d: (3,3) shape normalized array
array_d = np.arange(1, 10).reshape(3, 3)
normalized = (array_d - np.mean(array_d)) / np.std(array_d)
print("d. Original (3,3) shape array:")
print(array_d)
print("Normalized array:")
print(normalized)
print()

# Part e: (4,4) shape array and replace elements greater than 10 with 10
array_e = np.random.randint(1, 20, size=(4, 4))
print("e. Original array:")
print(array_e)
array_e[array_e > 10] = 10
print("Array with elements greater than 10 replace with 10:")
print(array_e)
print()

# Part f: Function to reverse 1D array and returns a new array
def reverse_array(array):
    return array[::-1]

array_f = np.array([1, 2, 3, 4, 5])
reversed_array = reverse_array(array_f)
print("f. Original array:", array_f)
print("Reversed array:", reversed_array)

a. (5,5) shape array with third column as 1:
[[10  5  1  1 12]
 [20  9  1  3  5]
 [ 2  4  1  4  9]
 [15 12  1 19  2]
 [ 7 10  1 20 12]]

b. (4,4) shape array with diagonal as 0:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]

c. Original (5,5) shape array:
[[47 79 70 29 56]
 [ 3 73 75 88 10]
 [93 54 34 80 39]
 [48 59 47 41 46]
 [97 38 85 64 90]]
Border elements: [47 79 70 29 56 10 39 46 90 64 85 38 97 48 93  3]
Corner elements: [47 56 97 90]

d. Original (3,3) shape array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]

e. Original array:
[[ 3 15  4  9]
 [16  8 19  5]
 [18  2 13 10]
 [ 5 18 19  1]]
Array with elements greater than 10 replace with 10:
[[ 3 10  4  9]
 [10  8 10  5]
 [10  2 10 10]
 [ 5 10 10  1]]

f. Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


**Question 03**

Performing statistical analysis on temperature data stored in NumPy arrays

In [46]:
# Part a: Store the average monthly temperatures of Baltimore
min_temps = np.array([30.5, 38.4, 48.1, 56.8, 65.2, 75.9, 83.6, 86.5, 75.3, 64.6, 58.1, 45.4])
max_temps = np.array([48.2, 50.3, 58.7, 61.9, 70.5, 82.4, 88.2, 93.1, 86.7, 77.5, 67.2, 53.6])
print("a. Stored the given information using NumPy arrays")

# Part b: Calculate yearly statistics for min and max temperatures
min_avg = min_temps.mean()
min_max = min_temps.max()
min_min = min_temps.min()

max_avg = max_temps.mean()
max_max = max_temps.max()
max_min = max_temps.min()
print("b. Yearly Statistics:")
print("Min Temperatures - Average:", min_avg, ", Max:", min_max, ", Min:", min_min)
print("Max Temperatures - Average:", max_avg, ", Max:", max_max, ", Min:", max_min)
print()

# Part c: Average temperatures in Q1 (Jan-Mar) and Q4 (Oct-Dec)
q1_min_avg = min_temps[:3].mean()
q1_max_avg = max_temps[:3].mean()

q4_min_avg = min_temps[-3:].mean()
q4_max_avg = max_temps[-3:].mean()

print("c. Quarterly Averages:")
print("Q1 (Jan-Mar) Min Avg:", q1_min_avg, ", Max Avg:", q1_max_avg)
print("Q4 (Oct-Dec) Min Avg:", q4_min_avg, ", Max Avg:", q4_max_avg)
print()

# Part d: Monthly average temperatures using mean() and dot product
monthly_avg_mean = (min_temps + max_temps) / 2
weights = np.array([0.5, 0.5])  # Equal weights for min and max
monthly_avg_dot = np.dot(np.vstack((min_temps, max_temps)).T, weights)

print("d. Monthly Average Temperatures:")
print("Using mean():", monthly_avg_mean)
print("Using dot product:", monthly_avg_dot)

a. Stored the given information using NumPy arrays
b. Yearly Statistics:
Min Temperatures - Average: 60.70000000000001 , Max: 86.5 , Min: 30.5
Max Temperatures - Average: 69.85833333333335 , Max: 93.1 , Min: 48.2

c. Quarterly Averages:
Q1 (Jan-Mar) Min Avg: 39.0 , Max Avg: 52.4
Q4 (Oct-Dec) Min Avg: 56.03333333333333 , Max Avg: 66.1

d. Monthly Average Temperatures:
Using mean(): [39.35 44.35 53.4  59.35 67.85 79.15 85.9  89.8  81.   71.05 62.65 49.5 ]
Using dot product: [39.35 44.35 53.4  59.35 67.85 79.15 85.9  89.8  81.   71.05 62.65 49.5 ]


**Question 04**

In [47]:
# Generate grades as an array of 60 random grades in the range of 60 through 100 and reshape to 20x3
grades = np.random.randint(60, 101, size=60).reshape(20, 3)
print("Original grades array (20 students x 3 exams):")
print(grades)
print()

# Part a: Average grades for each column (exam) and row (student)

col_averages = np.mean(grades, axis=0) # Average for each column (Midterm1, Midterm2, Final)
row_averages = np.mean(grades, axis=1) # Average for each row (students)

print("a. Column averages (Midterm1, Midterm2, Final):", col_averages)
print("Row averages (each student):", row_averages)
print()

# Part b: Maximum and minimum scores for Midterm1, Midterm 2 and Final
max_scores = np.max(grades, axis=0)
min_scores = np.min(grades, axis=0)
print("b. Maximum scores (Midterm1, Midterm2, Final):", max_scores)
print("Minimum scores (Midterm1, Midterm2, Final):", min_scores)
print()

Original grades array (20 students x 3 exams):
[[ 75  80  72]
 [ 89  91  95]
 [ 78  60  96]
 [ 78  95  60]
 [ 93  92  86]
 [ 63  91  68]
 [ 61  69  87]
 [ 78  76  65]
 [ 65  87  67]
 [ 81  66  62]
 [100  81  67]
 [ 71  91  72]
 [ 84  74  71]
 [ 93  86  77]
 [ 90  70  68]
 [ 70  68  83]
 [ 82  66  86]
 [ 74  98  78]
 [ 98  67  74]
 [ 88  63  81]]

a. Column averages (Midterm1, Midterm2, Final): [80.55 78.55 75.75]
Row averages (each student): [75.66666667 91.66666667 78.         77.66666667 90.33333333 74.
 72.33333333 73.         73.         69.66666667 82.66666667 78.
 76.33333333 85.33333333 76.         73.66666667 78.         83.33333333
 79.66666667 77.33333333]

b. Maximum scores (Midterm1, Midterm2, Final): [100  98  96]
Minimum scores (Midterm1, Midterm2, Final): [61 60 60]



**Part c:**
Calculating average grade of the first two and last two students can have two interpretations

**Interpretation 1:** Combined average for the first two students  
**Interpretation 2:** Individual averages for the first two students

But from part a we already got each students individual average, so I think for this question the combined group average (Interpretation 1) is most suitable.


In [48]:
# Part c: Average grade of first two and last two students
first_two_avg = np.mean(grades[:2])
last_two_avg = np.mean(grades[-2:])
print("c. First two students' average grade:", first_two_avg)
print("Last two students' average grade:", last_two_avg)

c. First two students' average grade: 83.66666666666667
Last two students' average grade: 78.5


In [49]:
# Part d: Average of Midterm 1 and 2 for the first 10 students
midterms_avg = np.mean(grades[:10, :2])
print("d. First 10 students Midterm 1 and 2 average:", midterms_avg)
print()

# Part e: All the students who received >=75 in midterm 2 or Final exam
high_scores = (grades[:, 1] >= 75) | (grades[:, 2] >= 75)
students_high = grades[high_scores]
print("e. Students with >=75 in Midterm2 or Final:")
print(students_high)
print()

# Part f: Change any scores <80 to 80, calculate average of Midterm1 and Final for alternate students

grades_80 = np.where(grades < 80, 80, grades) # Replacing scores <80 with 80

# Average of Midterm1 and Final for alternate students
alt_avg = np.mean(grades_80[::2, [0, 2]])

print("f. Average of Midterm1 and Final for alternate students after setting <80 to 80:", alt_avg)
print()

# Part g: Weighted(Weights: Midterm1 30%, Midterm2 30%, Final 40%) average for the first 10 students
weights = np.array([0.3, 0.3, 0.4])
weighted_avg = np.sum(grades[:10] * weights, axis=1)
print("g. Weighted averages for first 10 students:", weighted_avg)
print()

# Part h: Increase Midterms by 10%, decrease Final by 5%
adjusted_grades = grades.astype(float)  # Converted grades to float64 to handle multiplications by floats
adjusted_grades[:, :2] *= 1.1
adjusted_grades[:, 2] *= 0.95
print("h. Adjusted grades Midterms by 10%, decrease Final by 5%:")
print(adjusted_grades)
print()

# Part i: Rescale scores based on the maximum in each column
max_scores = np.max(grades, axis=0)
rescaled_grades = (grades / max_scores) * 100
print("i. Rescaled grades (based on column max):")
print(rescaled_grades)

d. First 10 students Midterm 1 and 2 average: 78.4

e. Students with >=75 in Midterm2 or Final:
[[ 75  80  72]
 [ 89  91  95]
 [ 78  60  96]
 [ 78  95  60]
 [ 93  92  86]
 [ 63  91  68]
 [ 61  69  87]
 [ 78  76  65]
 [ 65  87  67]
 [100  81  67]
 [ 71  91  72]
 [ 93  86  77]
 [ 70  68  83]
 [ 82  66  86]
 [ 74  98  78]
 [ 88  63  81]]

f. Average of Midterm1 and Final for alternate students after setting <80 to 80: 85.1

g. Weighted averages for first 10 students: [75.3 92.  79.8 75.9 89.9 73.4 73.8 72.2 72.4 68.9]

h. Adjusted grades Midterms by 10%, decrease Final by 5%:
[[ 82.5   88.    68.4 ]
 [ 97.9  100.1   90.25]
 [ 85.8   66.    91.2 ]
 [ 85.8  104.5   57.  ]
 [102.3  101.2   81.7 ]
 [ 69.3  100.1   64.6 ]
 [ 67.1   75.9   82.65]
 [ 85.8   83.6   61.75]
 [ 71.5   95.7   63.65]
 [ 89.1   72.6   58.9 ]
 [110.    89.1   63.65]
 [ 78.1  100.1   68.4 ]
 [ 92.4   81.4   67.45]
 [102.3   94.6   73.15]
 [ 99.    77.    64.6 ]
 [ 77.    74.8   78.85]
 [ 90.2   72.6   81.7 ]
 [ 81.4  107